### ISSUE TITLE
How to use it? (command 'keepContext.newTask' not found)

### ISSUE THREAD

**Issue by sgon00** [marlomgirardi/vscode-keep-context#1]
Hi, when I click `Create Task` button, it will just show an error message `command 'keepContext.newTask' not found`. How to use it properly? Thanks a lot. 

PS: I am running vscode environment (MacOS):

```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.6.0
```

**Comment by marlomgirardi** [comment]
I have just released a [hotfix (0.1.2)](https://github.com/marlomgirardi/vscode-keep-context/releases/tag/v0.1.2) can you check if it still happens?

To work properly you must open a project/workspace. If the same error happens, it might be something else in the extension bootstrap.

**Comment by sgon00** [comment]
@marlomgirardi Thanks a lot for your reply. From your last comment, I knew what I did wrong. I just use code to open a folder(directory). That's why it didn't work before. I never used code workspace before and have no idea why I should use it. After creating a workspace, this extension works fine. The extension README.md doesn't mention it only works in workspace so I don't know I have to use workspace. 

Btw, I am using https://github.com/jsaulou/vscode-tasks-context extension which works without workspace and use relative path for storing files path. So I would like to ask

(1) Why does this extension need to be based on workspace? I don't plan to use workspace.
(2) Can this extensions store relative path instead of absolute path? This is the main reason why I am looking for a context extension. I constantly change project directory(folder) name and move directory path and work on different computers with different directory file structure. The default vscode behavior can not handle these situations. With https://github.com/jsaulou/vscode-tasks-context, it proves that relative path record is actually possible. With relative path, I no longer need to worry about my project path and name anymore. 

Thanks a lot.

**Comment by marlomgirardi** [comment]
> @marlomgirardi Thanks a lot for your reply. From your last comment, I knew what I did wrong. I just use vscode to open a folder(directory). That's why it didn't work before. I never used vscode workspace before and have no idea why I should use it. After creating a workspace, this extension works fine. The extension README.md doesn't mention it only works in workspace so I don't know I have to use workspace. _(If this extension does not plan to support non-workspace case, I think the READEME.md should better be updated and clarify it only works on workspace)._

You don't need to explicitly create a workspace, you just need to open a folder (a project as I mentioned in the last comment) to work on.

> Btw, I am using https://github.com/jsaulou/vscode-tasks-context extension which works without workspace and use relative path for storing files path. So I would like to ask
> 
> (1) Why does this extension need to be based on workspace? I don't plan to use workspace.
> (2) Can this extension store relative path instead of absolute path? This is the main reason why I am looking for a context extension. I constantly change project directory name and move directory path and work on different computers with different directory file structure. The default vscode behavior can not handle these situations. With https://github.com/jsaulou/vscode-tasks-context, it proves that relative path record is actually possible. With relative path, I no longer need to worry about my project path and name anymore.

To answer your questions:
1. It works with workspace or project (single folder)
2. It actually is the right solution for that. I'm planning to do some changes, one of them is to use the VSCode storage instead of creating a file inside the project which is a bit annoying (I already have started). I just need to find some time to work on it.

About the `vscode-tasks-context`. It is a great tool but it doesn't work with workspaces and I use it a lot. Besides, it is more to manage tasks than context switches.

If you have time, feel free to contribute 😄

**Comment by sgon00** [comment]
@marlomgirardi Thanks a lot for the reply. 

1. I just tried it again. It doesn't work for project (single folder) (non-workspace case). With non-workspace single folder case, it will still show `command 'keepContext.newTask' not found` error message. To make sure I am using the latest version of the extension, I even tried to uninstall the extension and then reinstall it again. I can only use it with workspace. As long as I create a workspace, the error msg will be gone. 

2. Since I am a MacOS and Linux user, I really prefer(like) the way of creating a config file inside the project. *(Maybe windows users don't like this.)* Most apps on MacOS/Linux have this behavior. For instance, Finder.app (a MacOS explorer) will create a file called .DS_Store on every folder it opens. And the most important reason to support a config file inside the project is I can work on multiple computers. I can git push `keep-context.json` and `tasks-context.json` to my git repo and git pull on multiple computers. As long as I have vscode and the right extension installed on all computers, I can use the same contexts and tasks. I really want to use this extension as what you said, this extension is more to switch context than `vscode-tasks-context`, BUT if you plan to use VSCode storage instead of creating a file inside the project AND not plan to support **relative path**, I will not be able to use this extension. It's very important for me that the context will still work even if I rename the project folder name, change the folder path or moved to another computer. 

Thanks a lot for your time and answer. 😀

**Comment by marlomgirardi** [comment]
1. It is really weird, I have tried and it works as expected. I need to do some more tests to be sure. It might be about directory permissions.

2. I use MacOS and Linux as well and if you work alone, might be good for you to put it in the repository. But if you work with many developers I don't think that it is a good idea. I don't plan to support `keep-context.json` in the next version but I plan to support relative path.

Either way, thanks for your time 👍

**Comment by sgon00** [comment]
1. For `command 'keepContext.newTask' not found)` error. It can be easily reproduced by the following command on MacOS:

```shell
$ mkdir tmp
$ code tmp/
```

and then click `Create Task`, it will show the error message. 

2. If possible, you can provide an option to switch between the two storage types. For example, when `useVSCodeStorage` option is `true`, it uses VSCode storage and when it's `false`, it will create `keep-context.json`. If this is too much work, just ignore me. 

Thanks a lot.

**Comment by marlomgirardi** [comment]
I won't be able to work on it now, but if you want you can send a PR with this feature.

About the bug, I will take a look asap.

**Comment by tonich-sh** [comment]
I've got the same error. The problem is related to the file .vscode/keep-context.json. I've found that it is broken (currently i don't know why). Extension is not initialize properly due to exception on parsing this broken file. After i deleted it the extension starts and works fine again. PS: I didn't use a workspace for this project.

**Comment by marlomgirardi** [comment]
Yep, I have some commits that changed from `keep-context.json` to use workspace state and there we should have no problem. Just didn't had time to finish and test it properly.

**Comment by marlomgirardi** [comment]
A new release without `keep-context.json` was to be launched only in the v1.0.0 since it is a breaking change but I've done it now since there is not a lot of people using.

[`v0.2.0`](https://github.com/marlomgirardi/vscode-keep-context/releases/tag/v0.2.0)
