### ISSUE TITLE
Option to save under workspace

### ISSUE THREAD

**Issue by peter-kehl** [marlomgirardi/vscode-keep-context#14]
Thank you for Keep Context, Marlom.

Please, could it
- have a configuration field/option to save the tasks under the workspace's `.vscode/`? Ideally not in `settings.json`, but in its own file. And
- save the file paths (in that file under the workspace's `.vscode/`) as relative. Then people could share or back up the tasks.

**Comment by SamHasler** [comment]
Another use-case for this: when stored them in the `keep-contexts` file I often found I wanted to "migrate" files from one context to another, and having a file that I could easily find and edit made this very easy.

**Comment by marlomgirardi** [comment]
I've just published a new version, that should do the job.
I will close this one, let me know if works as expected 👍
