### ISSUE TITLE
Run into error on case sensitive filesystem

### ISSUE THREAD

**Issue by JITdev** [marlomgirardi/vscode-keep-context#16]
When I try to create new task on Linux/MacOS I get `command 'keepContext.newTask' not found` error. But any of the commands are the same.
Renaming files according to the code helps, but the real solution is a more consistent file naming method.

**Comment by marlomgirardi** [comment]
🤔 Cannot really reproduce this one, I also work on MacOS.
Can you provide a bit more info?

**Comment by JITdev** [comment]
So strange, it has been fixed by itself. Last time I reinstalled the problem disappeared.
Since I am not able to reproduce the error.
