### ISSUE TITLE
Does not work for me inside a workspace

### ISSUE THREAD

**Issue by Hoxbro** [marlomgirardi/vscode-keep-context#21]
I can't get this extension to work inside a workspace folder, I get the following error (an extra holoviews): 

``` 
Some files were not found in the file system:
/home/shh/Repos/holoviz/holoviews/holoviews/holoviews/plotting/bokeh/util.py
``` 

I can get it to work if I update the [`getFilePath`](https://github.com/marlomgirardi/vscode-keep-context/blob/10a08a76e8b64a210b6712e668bf4960c5054774/src/utils.ts#L90-L95) like this:

``` typescript
export function getFilePath(file: File) {
  if (!file.workspaceFolder) return file.relativePath;
  const workspacePath = getWorkspaceFolderFromName(file.workspaceFolder)?.uri.fsPath;
  if (!workspacePath) return null;
  return path.join(path.dirname(workspacePath), file.relativePath);
}
```

I think a check could be made if `path.join(path.dirname(workspacePath), file.relativePath)` exists, and if not, try `path.join(path.dirname(workspacePath), file.relativePath)`.

**Comment by marlomgirardi** [comment]
Thanks for the suggestion and it is now applied on v0.5.2 🙂
