### ISSUE TITLE
Hotkey to switch between tasks

### ISSUE THREAD

**Issue by Kwaadpepper** [marlomgirardi/vscode-keep-context#4]
Could you please add a hotkey to switch between tasks ?

ex: 

<kbd>alt+s</kbd> -> switch to next task from the list
<kbd>alt + p</kbd> -> switch to previous task from the list

And thank you for this plugin :)

**Comment by marlomgirardi** [comment]
It is already implemented and will be in the next release.
- Add task keybinding (Cmd+K Cmd+Shift+C).
- Select task keybinding (Cmd+K Cmd+Shift+S).
