### ISSUE TITLE
Creating task with no task active should add all open files into that task

### ISSUE THREAD

**Issue by SamHasler** [marlomgirardi/vscode-keep-context#8]
It's not a very good onboarding experience to have creating your first task close all the open editors when it's highly likely the user wanted to save their current context before moving on to something else.

**Comment by marlomgirardi** [comment]
True, I've spotted this one a while ago, I've even created a [task](https://github.com/marlomgirardi/vscode-keep-context/projects/2#card-26765978) for it

**Comment by marlomgirardi** [comment]
I don't know when I will do the next release but it has been added.
